-- ============================================================
-- Seed base del torneo — UTN GolMundial 2026 (RF28)
-- Generado automaticamente desde DataBase/seed-utn-golmundial-2026.json
-- (script Scripts/generar-seed.ps1). NO editar a mano: regenerar desde el JSON.
-- Carga: 16 sedes, 48 selecciones, 72 partidos de fase de grupos.
-- Uso: psql -U postgres -d utn_estadisticas -f seed-torneo-base.sql
-- ============================================================

BEGIN;

-- Sedes
INSERT INTO "Sedes" ("Id", "Nombre", "Ciudad", "Pais", "Capacidad") VALUES (1, 'Estadio Azteca (Estadio Ciudad de México)', 'Ciudad de México', 'México', 83000) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Sedes" ("Id", "Nombre", "Ciudad", "Pais", "Capacidad") VALUES (2, 'Estadio Akron (Estadio Guadalajara)', 'Zapopan', 'México', 48000) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Sedes" ("Id", "Nombre", "Ciudad", "Pais", "Capacidad") VALUES (3, 'Estadio BBVA (Estadio Monterrey)', 'Monterrey', 'México', 53500) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Sedes" ("Id", "Nombre", "Ciudad", "Pais", "Capacidad") VALUES (4, 'BMO Field (Toronto Stadium)', 'Toronto', 'Canadá', 45000) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Sedes" ("Id", "Nombre", "Ciudad", "Pais", "Capacidad") VALUES (5, 'BC Place (Vancouver Stadium)', 'Vancouver', 'Canadá', 54000) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Sedes" ("Id", "Nombre", "Ciudad", "Pais", "Capacidad") VALUES (6, 'MetLife Stadium (New York New Jersey Stadium)', 'East Rutherford', 'Estados Unidos', 82500) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Sedes" ("Id", "Nombre", "Ciudad", "Pais", "Capacidad") VALUES (7, 'SoFi Stadium (Los Angeles Stadium)', 'Inglewood', 'Estados Unidos', 70000) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Sedes" ("Id", "Nombre", "Ciudad", "Pais", "Capacidad") VALUES (8, 'AT&T Stadium (Dallas Stadium)', 'Arlington', 'Estados Unidos', 80000) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Sedes" ("Id", "Nombre", "Ciudad", "Pais", "Capacidad") VALUES (9, 'Mercedes-Benz Stadium (Atlanta Stadium)', 'Atlanta', 'Estados Unidos', 71000) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Sedes" ("Id", "Nombre", "Ciudad", "Pais", "Capacidad") VALUES (10, 'NRG Stadium (Houston Stadium)', 'Houston', 'Estados Unidos', 72000) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Sedes" ("Id", "Nombre", "Ciudad", "Pais", "Capacidad") VALUES (11, 'Gillette Stadium (Boston Stadium)', 'Foxborough', 'Estados Unidos', 65000) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Sedes" ("Id", "Nombre", "Ciudad", "Pais", "Capacidad") VALUES (12, 'Lincoln Financial Field (Philadelphia Stadium)', 'Filadelfia', 'Estados Unidos', 69000) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Sedes" ("Id", "Nombre", "Ciudad", "Pais", "Capacidad") VALUES (13, 'Hard Rock Stadium (Miami Stadium)', 'Miami Gardens', 'Estados Unidos', 65000) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Sedes" ("Id", "Nombre", "Ciudad", "Pais", "Capacidad") VALUES (14, 'Arrowhead Stadium (Kansas City Stadium)', 'Kansas City', 'Estados Unidos', 76000) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Sedes" ("Id", "Nombre", "Ciudad", "Pais", "Capacidad") VALUES (15, 'Levi''s Stadium (San Francisco Bay Area Stadium)', 'Santa Clara', 'Estados Unidos', 68500) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Sedes" ("Id", "Nombre", "Ciudad", "Pais", "Capacidad") VALUES (16, 'Lumen Field (Seattle Stadium)', 'Seattle', 'Estados Unidos', 68000) ON CONFLICT ("Id") DO NOTHING;

-- Selecciones
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (1, 'México', 'MEX', 'A', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (2, 'Corea del Sur', 'KOR', 'A', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (3, 'Sudáfrica', 'RSA', 'A', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (4, 'Chequia', 'CZE', 'A', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (5, 'Canadá', 'CAN', 'B', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (6, 'Bosnia y Herzegovina', 'BIH', 'B', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (7, 'Catar', 'QAT', 'B', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (8, 'Suiza', 'SUI', 'B', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (9, 'Brasil', 'BRA', 'C', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (10, 'Marruecos', 'MAR', 'C', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (11, 'Haití', 'HAI', 'C', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (12, 'Escocia', 'SCO', 'C', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (13, 'Estados Unidos', 'USA', 'D', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (14, 'Australia', 'AUS', 'D', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (15, 'Paraguay', 'PAR', 'D', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (16, 'Turquía', 'TUR', 'D', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (17, 'Alemania', 'GER', 'E', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (18, 'Ecuador', 'ECU', 'E', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (19, 'Costa de Marfil', 'CIV', 'E', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (20, 'Curazao', 'CUW', 'E', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (21, 'Países Bajos', 'NED', 'F', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (22, 'Japón', 'JPN', 'F', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (23, 'Túnez', 'TUN', 'F', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (24, 'Suecia', 'SWE', 'F', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (25, 'Bélgica', 'BEL', 'G', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (26, 'Irán', 'IRN', 'G', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (27, 'Egipto', 'EGY', 'G', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (28, 'Nueva Zelanda', 'NZL', 'G', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (29, 'España', 'ESP', 'H', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (30, 'Uruguay', 'URU', 'H', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (31, 'Arabia Saudita', 'KSA', 'H', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (32, 'Cabo Verde', 'CPV', 'H', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (33, 'Francia', 'FRA', 'I', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (34, 'Senegal', 'SEN', 'I', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (35, 'Noruega', 'NOR', 'I', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (36, 'Irak', 'IRQ', 'I', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (37, 'Argentina', 'ARG', 'J', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (38, 'Austria', 'AUT', 'J', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (39, 'Argelia', 'ALG', 'J', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (40, 'Jordania', 'JOR', 'J', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (41, 'Portugal', 'POR', 'K', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (42, 'Colombia', 'COL', 'K', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (43, 'Uzbekistán', 'UZB', 'K', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (44, 'RD Congo', 'COD', 'K', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (45, 'Inglaterra', 'ENG', 'L', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (46, 'Croacia', 'CRO', 'L', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (47, 'Panamá', 'PAN', 'L', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Selecciones" ("Id", "Nombre", "Codigo", "Grupo", "Escudo", "PartidosJugados", "PartidosGanados", "PartidosEmpatados", "PartidosPerdidos", "GolesFavor", "GolesContra", "Puntos") VALUES (48, 'Ghana', 'GHA', 'L', '', 0, 0, 0, 0, 0, 0, 0) ON CONFLICT ("Id") DO NOTHING;

-- Partidos (fase de grupos)
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (1, 1, 3, 1, '2026-06-11T19:00:00Z', 'GRUPOS', 'A', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (2, 2, 4, 2, '2026-06-12T02:00:00Z', 'GRUPOS', 'A', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (3, 5, 6, 4, '2026-06-12T19:00:00Z', 'GRUPOS', 'B', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (4, 13, 15, 7, '2026-06-13T01:00:00Z', 'GRUPOS', 'D', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (5, 7, 8, 15, '2026-06-13T19:00:00Z', 'GRUPOS', 'B', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (6, 9, 10, 6, '2026-06-13T22:00:00Z', 'GRUPOS', 'C', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (7, 11, 12, 11, '2026-06-14T01:00:00Z', 'GRUPOS', 'C', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (8, 14, 16, 5, '2026-06-14T04:00:00Z', 'GRUPOS', 'D', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (9, 17, 20, 10, '2026-06-14T17:00:00Z', 'GRUPOS', 'E', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (10, 21, 22, 8, '2026-06-14T20:00:00Z', 'GRUPOS', 'F', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (11, 19, 18, 12, '2026-06-14T23:00:00Z', 'GRUPOS', 'E', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (12, 24, 23, 3, '2026-06-15T02:00:00Z', 'GRUPOS', 'F', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (13, 29, 32, 9, '2026-06-15T16:00:00Z', 'GRUPOS', 'H', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (14, 25, 27, 16, '2026-06-15T19:00:00Z', 'GRUPOS', 'G', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (15, 31, 30, 13, '2026-06-15T22:00:00Z', 'GRUPOS', 'H', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (16, 26, 28, 7, '2026-06-16T01:00:00Z', 'GRUPOS', 'G', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (17, 33, 34, 6, '2026-06-16T19:00:00Z', 'GRUPOS', 'I', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (18, 36, 35, 11, '2026-06-16T22:00:00Z', 'GRUPOS', 'I', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (19, 37, 39, 14, '2026-06-17T01:00:00Z', 'GRUPOS', 'J', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (20, 38, 40, 15, '2026-06-17T04:00:00Z', 'GRUPOS', 'J', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (21, 41, 44, 10, '2026-06-17T17:00:00Z', 'GRUPOS', 'K', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (22, 45, 46, 8, '2026-06-17T20:00:00Z', 'GRUPOS', 'L', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (23, 48, 47, 4, '2026-06-17T23:00:00Z', 'GRUPOS', 'L', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (24, 43, 42, 1, '2026-06-18T02:00:00Z', 'GRUPOS', 'K', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (25, 4, 3, 9, '2026-06-18T16:00:00Z', 'GRUPOS', 'A', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (26, 8, 6, 7, '2026-06-18T19:00:00Z', 'GRUPOS', 'B', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (27, 5, 7, 5, '2026-06-18T22:00:00Z', 'GRUPOS', 'B', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (28, 1, 2, 2, '2026-06-19T01:00:00Z', 'GRUPOS', 'A', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (29, 13, 14, 16, '2026-06-19T19:00:00Z', 'GRUPOS', 'D', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (30, 12, 10, 11, '2026-06-19T22:00:00Z', 'GRUPOS', 'C', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (31, 9, 11, 12, '2026-06-20T00:30:00Z', 'GRUPOS', 'C', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (32, 16, 15, 15, '2026-06-20T03:00:00Z', 'GRUPOS', 'D', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (33, 21, 24, 10, '2026-06-20T17:00:00Z', 'GRUPOS', 'F', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (34, 17, 19, 4, '2026-06-20T20:00:00Z', 'GRUPOS', 'E', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (35, 18, 20, 14, '2026-06-21T00:00:00Z', 'GRUPOS', 'E', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (36, 23, 22, 3, '2026-06-21T04:00:00Z', 'GRUPOS', 'F', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (37, 29, 31, 9, '2026-06-21T16:00:00Z', 'GRUPOS', 'H', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (38, 25, 26, 7, '2026-06-21T19:00:00Z', 'GRUPOS', 'G', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (39, 30, 32, 13, '2026-06-21T22:00:00Z', 'GRUPOS', 'H', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (40, 28, 27, 5, '2026-06-22T01:00:00Z', 'GRUPOS', 'G', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (41, 37, 38, 8, '2026-06-22T17:00:00Z', 'GRUPOS', 'J', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (42, 33, 36, 12, '2026-06-22T21:00:00Z', 'GRUPOS', 'I', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (43, 35, 34, 6, '2026-06-23T00:00:00Z', 'GRUPOS', 'I', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (44, 40, 39, 15, '2026-06-23T03:00:00Z', 'GRUPOS', 'J', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (45, 41, 43, 10, '2026-06-23T17:00:00Z', 'GRUPOS', 'K', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (46, 45, 48, 11, '2026-06-23T20:00:00Z', 'GRUPOS', 'L', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (47, 47, 46, 4, '2026-06-23T23:00:00Z', 'GRUPOS', 'L', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (48, 42, 44, 2, '2026-06-24T02:00:00Z', 'GRUPOS', 'K', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (49, 8, 5, 5, '2026-06-24T19:00:00Z', 'GRUPOS', 'B', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (50, 6, 7, 16, '2026-06-24T19:00:00Z', 'GRUPOS', 'B', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (51, 12, 9, 13, '2026-06-24T22:00:00Z', 'GRUPOS', 'C', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (52, 10, 11, 9, '2026-06-24T22:00:00Z', 'GRUPOS', 'C', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (53, 4, 1, 1, '2026-06-25T01:00:00Z', 'GRUPOS', 'A', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (54, 3, 2, 3, '2026-06-25T01:00:00Z', 'GRUPOS', 'A', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (55, 20, 19, 12, '2026-06-25T20:00:00Z', 'GRUPOS', 'E', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (56, 18, 17, 6, '2026-06-25T20:00:00Z', 'GRUPOS', 'E', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (57, 22, 24, 8, '2026-06-25T23:00:00Z', 'GRUPOS', 'F', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (58, 23, 21, 14, '2026-06-25T23:00:00Z', 'GRUPOS', 'F', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (59, 16, 13, 7, '2026-06-26T02:00:00Z', 'GRUPOS', 'D', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (60, 15, 14, 15, '2026-06-26T02:00:00Z', 'GRUPOS', 'D', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (61, 35, 33, 11, '2026-06-26T19:00:00Z', 'GRUPOS', 'I', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (62, 34, 36, 4, '2026-06-26T19:00:00Z', 'GRUPOS', 'I', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (63, 32, 31, 10, '2026-06-27T00:00:00Z', 'GRUPOS', 'H', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (64, 30, 29, 2, '2026-06-27T00:00:00Z', 'GRUPOS', 'H', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (65, 27, 26, 16, '2026-06-27T03:00:00Z', 'GRUPOS', 'G', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (66, 28, 25, 5, '2026-06-27T03:00:00Z', 'GRUPOS', 'G', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (67, 47, 45, 6, '2026-06-27T21:00:00Z', 'GRUPOS', 'L', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (68, 46, 48, 12, '2026-06-27T21:00:00Z', 'GRUPOS', 'L', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (69, 42, 41, 13, '2026-06-27T23:30:00Z', 'GRUPOS', 'K', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (70, 44, 43, 9, '2026-06-27T23:30:00Z', 'GRUPOS', 'K', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (71, 39, 38, 14, '2026-06-28T02:00:00Z', 'GRUPOS', 'J', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;
INSERT INTO "Partidos" ("Id", "SeleccionLocalId", "SeleccionVisitanteId", "SedeId", "FechaHora", "Fase", "Grupo", "Estado", "GolesLocal", "GolesVisitante") VALUES (72, 40, 37, 8, '2026-06-28T02:00:00Z', 'GRUPOS', 'J', 'programado', NULL, NULL) ON CONFLICT ("Id") DO NOTHING;

-- Resincronizar secuencias IDENTITY para que los próximos INSERT (vía API) no choquen con estos IDs
SELECT setval(pg_get_serial_sequence('"Sedes"', 'Id'), COALESCE((SELECT MAX("Id") FROM "Sedes"), 1));
SELECT setval(pg_get_serial_sequence('"Selecciones"', 'Id'), COALESCE((SELECT MAX("Id") FROM "Selecciones"), 1));
SELECT setval(pg_get_serial_sequence('"Partidos"', 'Id'), COALESCE((SELECT MAX("Id") FROM "Partidos"), 1));

COMMIT;

